server:
  port: 8099
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: root
    password: root

    url: jdbc:mysql://47.92.221.53:3306/epi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    root: warn